"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navbar from "@/components/Navbar";


interface Persona {
  name: string;
  age: number;
  profession: string;
  goals: string[];
  pain_points: string[];
  why_use: string;
}

interface MarketInsights {
  estimated_market_size: string;
  growth_trends: string[];
  why_attractive: string;
}

interface Competitor {
  name: string;
  description: string;
  strengths: string[];
  weaknesses: string[];
}

interface ValidationScore {
  score: number;
  breakdown: {
    market_demand: number;
    innovation: number;
    competition: number;
    feasibility: number;
  };
  explanation: string;
}

interface AnalysisData {
  personas: Persona[];
  market_insights: MarketInsights;
  competitors: Competitor[];
  moat: string;
  validation_score: ValidationScore;
  pitch: string;
  customer_feedback: string[];
}

interface IdeaData {
  title: string;
  problem: string;
  audience: string;
  solution: string;
  industry: string;
  revenue_model: string;
}

// Circular score component
function ScoreCircle({ score }: { score: number }) {
  const radius = 45;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;
  const color =
    score >= 70 ? "#c9a55c" : score >= 50 ? "#e2c882" : "#b4838d";

  return (
    <div className="relative w-40 h-40 mx-auto">
      <svg className="w-40 h-40 -rotate-90" viewBox="0 0 100 100">
        <circle
          cx="50"
          cy="50"
          r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.05)"
          strokeWidth="8"
        />
        <circle
          cx="50"
          cy="50"
          r={radius}
          fill="none"
          stroke={color}
          strokeWidth="8"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          style={{
            transition: "stroke-dashoffset 1.5s ease-in-out",
            filter: `drop-shadow(0 0 8px ${color}80)`,
          }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-4xl font-bold" style={{ color }}>
          {score}
        </span>
        <span className="text-gray-500 text-sm">/ 100</span>
      </div>
    </div>
  );
}

// Score breakdown bar
function ScoreBar({ label, value }: { label: string; value: number }) {
  const color =
    value >= 70 ? "bg-amber-500" : value >= 50 ? "bg-amber-300" : "bg-rose-400";

  return (
    <div>
      <div className="flex justify-between text-sm mb-1">
        <span className="text-gray-400">{label}</span>
        <span className="text-white font-medium">{value}</span>
      </div>
      <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full ${color} transition-all duration-1000 ease-out`}
          style={{ width: `${value}%` }}
        />
      </div>
    </div>
  );
}

export default function DashboardPage() {
  const router = useRouter();
  const [analysis, setAnalysis] = useState<AnalysisData | null>(null);
  const [idea, setIdea] = useState<IdeaData | null>(null);
  const [copied, setCopied] = useState(false);
  const dashboardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const storedAnalysis = sessionStorage.getItem("valtrix_analysis");
    const storedIdea = sessionStorage.getItem("valtrix_idea");

    if (!storedAnalysis) {
      router.push("/validate");
      return;
    }

    setAnalysis(JSON.parse(storedAnalysis));
    if (storedIdea) setIdea(JSON.parse(storedIdea));
  }, [router]);

  // Scroll reveal
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("visible");
          }
        });
      },
      { threshold: 0.05 }
    );

    const elements = dashboardRef.current?.querySelectorAll(".reveal");
    elements?.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, [analysis]);

  const copyPitch = () => {
    if (analysis?.pitch) {
      navigator.clipboard.writeText(analysis.pitch);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const exportPitch = () => {
    if (!analysis || !idea) return;
    const text = `INVESTOR PITCH — ${idea.title}\n${"=".repeat(50)}\n\n${analysis.pitch}\n\n---\nGenerated by Valtrix — AI Startup Co-Pilot\nValidation Score: ${analysis.validation_score.score}/100`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${idea.title.replace(/\s+/g, "_")}_pitch.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!analysis) {
    return (
      <main className="min-h-screen bg-background flex items-center justify-center">
        <div className="glass p-8 text-center">
          <div className="w-12 h-12 border-2 border-accent border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-400">Loading analysis...</p>
        </div>
      </main>
    );
  }

  return (
    <main className="relative min-h-screen bg-background text-foreground">
      <Navbar />
      <div className="bg-orb-1" />
      <div className="bg-orb-2" />
      <div className="bg-orb-3" />

      <div ref={dashboardRef} className="relative z-10 pt-28 pb-20 px-6">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12 reveal">
            <div className="inline-flex items-center gap-2 glass px-4 py-2 mb-4 text-sm text-gray-400">
              <span className="w-2 h-2 rounded-full bg-amber-400" />
              Analysis Complete
            </div>
            <h1 className="text-3xl md:text-5xl font-bold mb-2">
              Startup <span className="gradient-text">Blueprint</span>
            </h1>
            {idea && (
              <p className="text-gray-400 text-lg">{idea.title}</p>
            )}
          </div>

          {/* Idea Summary */}
          {idea && (
            <section className="mb-12 reveal">
              <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-amber-500 to-amber-700 flex items-center justify-center text-sm">
                  💡
                </span>
                Idea Summary
              </h2>
              <div className="glass p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <span className="text-xs text-gray-500 uppercase tracking-wider">Problem</span>
                  <p className="text-gray-300 mt-1">{idea.problem}</p>
                </div>
                <div>
                  <span className="text-xs text-gray-500 uppercase tracking-wider">Solution</span>
                  <p className="text-gray-300 mt-1">{idea.solution}</p>
                </div>
                <div>
                  <span className="text-xs text-gray-500 uppercase tracking-wider">Target Audience</span>
                  <p className="text-gray-300 mt-1">{idea.audience}</p>
                </div>
                <div>
                  <span className="text-xs text-gray-500 uppercase tracking-wider">Industry</span>
                  <p className="text-gray-300 mt-1">{idea.industry}</p>
                </div>
              </div>
            </section>
          )}

          {/* Validation Score */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-emerald-700 flex items-center justify-center text-sm">
                ✅
              </span>
              Validation Score
            </h2>
            <div className="glass p-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                <ScoreCircle score={analysis.validation_score.score} />
                <div className="space-y-4">
                  <ScoreBar label="Market Demand" value={analysis.validation_score.breakdown.market_demand} />
                  <ScoreBar label="Innovation" value={analysis.validation_score.breakdown.innovation} />
                  <ScoreBar label="Competition" value={analysis.validation_score.breakdown.competition} />
                  <ScoreBar label="Feasibility" value={analysis.validation_score.breakdown.feasibility} />
                </div>
              </div>
              <p className="text-gray-400 mt-6 text-sm leading-relaxed">
                {analysis.validation_score.explanation}
              </p>
            </div>
          </section>

          {/* User Personas */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-amber-400 to-yellow-600 flex items-center justify-center text-sm">
                👥
              </span>
              User Personas
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {analysis.personas.map((persona, i) => (
                <div key={i} className="glass glass-hover p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-amber-500/30 to-rose-400/30 flex items-center justify-center text-lg font-bold text-white">
                      {persona.name.charAt(0)}
                    </div>
                    <div>
                      <h3 className="font-semibold text-white">{persona.name}</h3>
                      <p className="text-xs text-gray-500">
                        {persona.age} · {persona.profession}
                      </p>
                    </div>
                  </div>

                  <div className="mb-3">
                    <span className="text-xs text-amber-400 font-medium uppercase tracking-wider">
                      Goals
                    </span>
                    <ul className="mt-1 space-y-1">
                      {persona.goals.map((goal, j) => (
                        <li key={j} className="text-sm text-gray-400 flex items-start gap-2">
                          <span className="text-amber-400 mt-0.5">→</span>
                          {goal}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="mb-3">
                    <span className="text-xs text-rose-300 font-medium uppercase tracking-wider">
                      Pain Points
                    </span>
                    <ul className="mt-1 space-y-1">
                      {persona.pain_points.map((point, j) => (
                        <li key={j} className="text-sm text-gray-400 flex items-start gap-2">
                          <span className="text-rose-300 mt-0.5">•</span>
                          {point}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="pt-3 border-t border-white/5">
                    <p className="text-sm text-gray-500 italic">
                      &ldquo;{persona.why_use}&rdquo;
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Market Insights */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-rose-300 to-rose-500 flex items-center justify-center text-sm">
                📊
              </span>
              Market Insights
            </h2>
            <div className="glass p-6">
              <div className="flex items-center gap-4 mb-6">
                <div className="glass px-6 py-3 text-center">
                  <div className="text-2xl font-bold gradient-text">
                    {analysis.market_insights.estimated_market_size}
                  </div>
                  <div className="text-xs text-gray-500 mt-1">Estimated Market Size</div>
                </div>
              </div>

              <div className="mb-4">
                <h3 className="text-sm font-medium text-gray-300 mb-2">Growth Trends</h3>
                <ul className="space-y-2">
                  {analysis.market_insights.growth_trends.map((trend, i) => (
                    <li key={i} className="text-sm text-gray-400 flex items-start gap-2">
                      <span className="text-amber-400 mt-0.5">↗</span>
                      {trend}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="pt-4 border-t border-white/5">
                <h3 className="text-sm font-medium text-gray-300 mb-2">Why This Market Is Attractive</h3>
                <p className="text-sm text-gray-400 leading-relaxed">
                  {analysis.market_insights.why_attractive}
                </p>
              </div>
            </div>
          </section>

          {/* Competitors */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-yellow-600 to-amber-700 flex items-center justify-center text-sm">
                🔍
              </span>
              Competitor Analysis
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {analysis.competitors.map((comp, i) => (
                <div key={i} className="glass glass-hover p-6">
                  <h3 className="text-lg font-semibold text-white mb-2">{comp.name}</h3>
                  <p className="text-sm text-gray-500 mb-4">{comp.description}</p>

                  <div className="mb-3">
                    <span className="text-xs text-emerald-400 font-medium uppercase tracking-wider">
                      Strengths
                    </span>
                    <ul className="mt-1 space-y-1">
                      {comp.strengths.map((s, j) => (
                        <li key={j} className="text-sm text-gray-400 flex items-start gap-2">
                          <span className="text-emerald-400 mt-0.5">+</span>
                          {s}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <span className="text-xs text-red-400 font-medium uppercase tracking-wider">
                      Weaknesses
                    </span>
                    <ul className="mt-1 space-y-1">
                      {comp.weaknesses.map((w, j) => (
                        <li key={j} className="text-sm text-gray-400 flex items-start gap-2">
                          <span className="text-red-400 mt-0.5">−</span>
                          {w}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Startup Moat */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-stone-400 to-stone-600 flex items-center justify-center text-sm">
                🏰
              </span>
              Startup Moat
            </h2>
            <div className="glass p-6">
              <p className="text-gray-300 leading-relaxed">{analysis.moat}</p>
            </div>
          </section>

          {/* Investor Pitch */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-amber-400 to-rose-400 flex items-center justify-center text-sm">
                🎤
              </span>
              Investor Pitch
            </h2>
            <div className="glass-strong p-8 relative overflow-hidden">
              <div className="absolute -top-10 -right-10 w-40 h-40 bg-amber-500/10 rounded-full blur-[60px]" />
              <p className="text-gray-200 text-lg leading-relaxed relative z-10 mb-6">
                &ldquo;{analysis.pitch}&rdquo;
              </p>
              <div className="flex gap-3 relative z-10">
                <button
                  onClick={copyPitch}
                  className="btn-secondary !py-2 !px-4 text-sm flex items-center gap-2"
                >
                  {copied ? (
                    <>
                      <svg className="w-4 h-4 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      Copied!
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                      </svg>
                      Copy Pitch
                    </>
                  )}
                </button>
                <button
                  onClick={exportPitch}
                  className="btn-secondary !py-2 !px-4 text-sm flex items-center gap-2"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Export Pitch
                </button>
              </div>
            </div>
          </section>

          {/* Customer Feedback */}
          <section className="mb-12 reveal">
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
              <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-amber-300 to-amber-500 flex items-center justify-center text-sm">
                💬
              </span>
              Simulated Customer Feedback
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {analysis.customer_feedback.map((feedback, i) => (
                <div key={i} className="glass glass-hover p-6">
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-amber-500/30 to-rose-400/30 flex items-center justify-center text-xs font-bold text-white">
                      U{i + 1}
                    </div>
                    <div>
                      <div className="text-sm font-medium text-white">User {i + 1}</div>
                      <div className="text-xs text-gray-600">Potential Customer</div>
                    </div>
                  </div>
                  <p className="text-sm text-gray-400 italic leading-relaxed">
                    &ldquo;{feedback}&rdquo;
                  </p>
                </div>
              ))}
            </div>
          </section>

          {/* Actions */}
          <div className="text-center reveal">
            <div className="glass-strong p-8 inline-block">
              <p className="text-gray-400 mb-4">Want to validate another idea?</p>
              <Link href="/validate" className="btn-primary inline-block">
                Validate Another Idea
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}